# Generated by Django 2.2 on 2019-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190906_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('article', 'Article'), ('map', 'Map')], default='article', max_length=10),
        ),
    ]
